### ISSUE TITLE
Realease problemas

### ISSUE THREAD

**Issue by Serck96** [Rainbow-CPaaS/Rainbow-CSharp-SDK-Samples#2]
When compiling my app for publication there is no problem, but when it is run it just closes. It is a Xamarin Forms app and the problem occurs only in Android, in realese compilation, in debug compilation there are no problems

**Comment by ChristopheI** [comment]
Hi,
I notice in the SDK that some calls to "Assembly" object are not authorized in Android, iOS or UWP context.
It should be fixed in version 2.1.0 of the SDK.
Regards.

**Comment by ChristopheI** [comment]
Do you still have the pb ?
