### ISSUE TITLE
Getting an exception when trying to send a message 

### ISSUE THREAD

**Issue by mctsnt** [Rainbow-CPaaS/Rainbow-CSharp-SDK-Samples#27]
Hello, when testing out this code and using it to send a message to a conversation, I am getting the following exception **"Object reference not set to an instance of an object."** and here is the stack trace the SDK is providing me:

`   at Rainbow.InstantMessaging.SendMessage(Conversation conversation, Message& message)
   at Rainbow.InstantMessaging.SendMessageToConversationId(String conversationId, String message, List 1 mentions, UrgencyType urgency, Geolocation geolocation, Action 1 callback)`

However in debugging I can see that both the conversation Id and the test message are set, so I cannot understand where there is a problem?

**Comment by ChristopheI** [comment]
Hi,

Which example are you trying ?

Did you change the code sample or not ?

If you have changed it:

- could you share some part of your code ?

- could you make a break point in your callback to ensure the exception is not raised in this part ?

**Comment by ChristopheI** [comment]
Hi Maritina,

Since last update of the sample, it's working on you side, isn't it ?

Can I close te issue ?

Thx

**Comment by mctsnt** [comment]
Hello, 
Yes you're right the new update is working so I'll close the issue, thank you again!
