### ISSUE TITLE
async / await instead of callbacks in the .NET SDK

### ISSUE THREAD

**Issue by ssteiner** [Rainbow-CPaaS/Rainbow-CSharp-SDK-Samples#39]
Have you given any thought of using the standard async/away approach with Task<T> results rather than synchronous events with a callback? the .NET SDK is kind of a throwback to the old way of doing async with `BeginXX` and `EndXX` methods that has been  superseded with async/await back in .NET 4.x.

Might even be something that the community can do if you'd provide the code.

**Comment by ChristopheI** [comment]
Async/away approach is in my top list of priorities.
The next major release will use them.
Focus is done, for the moment, on WebRTC features.

**Comment by ChristopheI** [comment]
This week a new version (v3.x) will be available with Async/Await pattern - for the moment in STS before to reach LTS.
V3.x will be the only to have new features

V2.6.24  will be also available this week.
V2.6.4+ will now contain only fix and it will be obsolete in 6 months.
